version: '3.9'

services:
workspace:
container_name: java-workspace
build:
context: ./docker/workspace
args:
USERNAME:${USERNAME}
  my-spring-boot-app:
    image: my-spring-boot-app
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default
